name: GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: janosh/workflows/.github/workflows/nodejs-gh-pages.yml@main
    secrets: inherit
    with:
      install-cmd: npm install --force
